#!/bin/sh

echo "Atualizando repositórios..."
if ! sudo apt update
then
    echo "Não foi possível atualizar os repositórios. Verifique seu arquivo /etc/apt/sources.list"
    exit 1
fi
echo "Atualização feita com sucesso"

echo "Atualizando pacotes já instalados"
if ! sudo apt full-upgrade -y
then
    echo "Não foi possível atualizar pacotes."
    exit 1
fi
clear
echo "Atualização de pacotes feita com sucesso"
