#!/bin/bash

echo "Removendo Xonsh..."
sudo rm -rf /usr/local/bin/xon.sh
sudo rm -rf /usr/local/bin/xonsh
sudo rm -rf /usr/local/bin/xonsh-cat
sudo rm -rf /usr/local/lib/python3.6/dist-packages/xonsh
sudo rm -rf /usr/local/lib/python3.6/dist-packages/xonsh-0.9.10.egg-info
sudo rm -rf /usr/local/lib/python3.6/dist-packages/xontrib
sudo rm -rf /home/restinga/.config/xonsh
sudo rm -rf /home/restinga/.local/share/xonsh
echo "Xonsh removido por completo"
