#!/bin/sh

echo "Parando Serviços LXC/LXD"

echo "Parando LXC"
systemctl stop lxc.service
systemctl stop lxc-net.service
systemctl stop lxcfs.service

echo "Parando LXD"
systemctl stop lxd.service
systemctl stop lxd-containers.service
