#!/bin/sh

Menu() {
clear
echo "Ferramenta de SWAP"
echo
echo " Opções:"
echo " 1. SWAP ON"
echo " 2. SWAP OFF"
echo " 3. CLEAN SWAP"
echo " 4. SAIR"
echo
printf "Esolha uma opção: "
read -r OPTION
echo
case $OPTION in
    1)
	  echo "Ligando SWAP"
      cd /media/restinga/SD/
      sudo swapon /swapfile
      echo "SWAP ligado"
			;;
    2)
      echo "Desligando SWAP"
      cd /media/restinga/SD/
      sudo swapoff /swapfile
      echo "SWAP desligado"
      ;;
    3)
      echo "Limpando SWAP"
      sudo swapoff -a
      cd /media/restinga/SD/
      sudo swapon /swapfile
      ;;
    4)
      exit
      ;;
    *) echo "Opção inválida" ;;
esac

echo
printf "Sair? [S/N] "
read -r SAIR
echo
case $SAIR in
    s|S|...) exit ;;
    n|N|"") Menu ;;
    *) echo "Opção inválida" ;;
esac
}
clear
Menu
